<h3><?php echo $this->_('User View Panel'); ?></h3>
<br/><br/>

<form class="form" onsubmit="return check_form();" action="<?php echo $this->url(array(
		'controller' => 'user', 
		'action' => 'postsave', 
		'module' => 'admin'
		), null , true);?>" method="post" id="form">

<input type="hidden" name="id" value="<?php echo $this->user['id']; ?>"/>


		<p>
			<label for="name"><?php echo $this->_("First Name")?>:*</label>
			<input class="text" name="first_name" id="first_name" type="text" value="<?php echo $this->user['first_name']?>" />
		</p>
		<p>
			<label for="email"><?php echo $this->_("Last Name")?>:*</label>
			<input class="text" name="last_name" id="last_name" type="text" value="<?php echo $this->user['last_name']?>" />
		</p>
		
		
		<p>
			<label for="email"><?php echo $this->_("E-mail")?>:*</label>
			<input class="text" name="email" id="email" type="text" value="<?php echo $this->user['email']?>" />
		</p>
		
		<p>
			<label for="email"><?php echo $this->_("Job Description")?>:*</label>
			<input type="text" class="text" name="job_desc" id="job_desc" value="<?php echo $this->user['job_desc']?>" >
		</p>

		<p>
		<label></label>
		<input type="submit" value="<?php echo $this->_('Submit'); ?>" />
		</p>


</form>

<script type="text/javascript">
//<!-- 

	function check_form(){
	
		var first_name = $("#first_name").val();
		var isEmpty = rocknoon.validate.is_empty( first_name );
		if( isEmpty ){
			show_error( "first_name_error" , '<?php echo $this->_("You should input your first name!");?>' );
			return false;			
		}
	
		var last_name = $("#last_name").val();
		var isEmpty = rocknoon.validate.is_empty( last_name );
		if( isEmpty ){
			show_error( "last_name_error" , '<?php echo $this->_("You should input your last name!");?>' );
			return false;			
		}
	
		var email = $("#email").val();
		var isEmail = rocknoon.validate.is_email( email );
		if( !isEmail ){
			show_error( "email_error" , '<?php echo $this->_("You should input a right email address!");?>' );
			return false;			
		}
	
		
	
		var job_desc = $("#job_desc").val();
		var isEmpty = rocknoon.validate.is_empty( job_desc );
		if( isEmpty ){
			show_error( "job_desc_error" , '<?php echo $this->_("You should input your job description!");?>' );
			return false;			
		}
	
		
	
		return true;
		
	}
	
	function show_error( id , error ){
		alert( error );
	
	}
	
	function on_complete_check_email( response ){
	
		var rst = rocknoon.ajax.prase(response);
		if( rst.status ){
			if( rst.info == 1 ){
				show_error( "email_error" , "<?php echo $this->_("Email already exist!")?>" );
			}else{
				$("#form").submit();
			}
		}else{
			alert( rst.info );
		}
		
	}
	

//--> 
</script>
