<h3><?php echo $this->_('User Panel'); ?></h3>

<form class="form" action="#" >

<p>
	<label><?php echo $this->_('Email'); ?></label>
	<?php echo $this->user['email']?>
</p>

<p>
	<label for="name"><?php echo $this->_("Status")?>:</label>
	<?php echo $this->user["status_name"]?>
</p>

<p>
	<label for="name"><?php echo $this->_("Role")?>:</label>
	<?php echo $this->user["role_name"]?>
</p>

<p>
	<label><?php echo $this->_('First Name'); ?></label>
	<?php echo $this->user['first_name']?>
</p>

<p>
	<label><?php echo $this->_('Last Name'); ?></label>
	<?php echo $this->user['last_name']?>
</p>


<p>
	<label><?php echo $this->_('Job Description'); ?></label>
	<?php echo $this->user['job_desc']?>
</p>

<p>
	<label><?php echo $this->_('Create Time'); ?></label>
	<?php echo date('Y-m-d' , $this->user['date_add']); ?>
</p>

<p>
	<label><?php echo $this->_('Action'); ?></label>
	<?php if( intval($this->user['status'] ) === Narrow_User_Imple::STATUS_WAITING ): ?>
		<a href="javascript:void(0);" onclick="reject(<?php echo $this->user['id']?>);"><?php echo $this->_('Reject');?></a> |
		<a href="javascript:void(0);" onclick="approve(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_USER?>);"> <?php echo $this->_('Default Approve');?></a> | 
		<a href="javascript:void(0);" onclick="approve(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_ADMIN?>);"><?php echo $this->_('Admin Approve');?></a> 
		<?php endif;?>
		<?php if( intval($this->user['status'] )  === Narrow_User_Imple::STATUS_APPROVAL ):?>
			<a href="javascript:void(0);" onclick="reject(<?php echo $this->user['id']?>);"><?php echo $this->_('Reject');?></a>  | 	
			<?php if( $this->user['role'] == Narrow_User_Imple::ROLE_USER ):?>
				<a href="javascript:void(0);" onclick="change_role(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_ADMIN?>);" ><?php echo $this->_('To Admin');?></a> 
			<?php endif;?>
			<?php if( $this->user['role'] == Narrow_User_Imple::ROLE_ADMIN ):?>
				<a href="javascript:void(0);" onclick="change_role(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_USER?>);"><?php echo $this->_('To Default');?></a> 
			<?php endif;?>
		<?php endif?>
		
		<?php if( intval($this->user['status'] )  === Narrow_User_Imple::STATUS_REJECTED ):?>
			<a href="javascript:void(0);" onclick="approve(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_USER?>);"> <?php echo $this->_('Default Approve');?></a> | 
			<a href="javascript:void(0);" onclick="approve(<?php echo $this->user['id']?> , <?php echo Narrow_User_Imple::ROLE_ADMIN?>);"><?php echo $this->_('Admin Approve');?></a>  
			
		<?php endif;?>
	
</p>





</form>


<script>

	function reject( id ){
		var answer = confirm("<?php echo $this->_("Are you sure you want to reject this user? ")?>");
		if(answer){
			location.href = __BASE_URL__ + "/admin/user/postreject/id/" + id;
		}
	}

	function approve( id , role ){
		var answer = confirm("<?php echo $this->_("Are you sure you want to approve this user? ")?>");
		if(answer){
			location.href = __BASE_URL__ + "/admin/user/postapprove/id/" + id + "/role/" + role;
		}
	}

	function change_role( id , role ){
		var answer = confirm("<?php echo $this->_("Are you sure you want to change user's role? ")?>");
		if(answer){
			location.href = __BASE_URL__ + "/admin/user/postrole/id/" + id + "/role/" + role;
		}
	}


</script>


