<?php if( $this->success ) :?>
<div class=success>
	<?php echo( $this->success )?>
</div>
<?php endif;?>


<?php if( $this->error ) :?>
<div class="error">
	<?php echo( $this->error )?>
</div>
<?php endif;?>


<div id="panel">
		<h2>TV Mundipharma Login</h2>
		<form class="form" action="<?php echo $this->url(array('action' => 'postlogin' , 'controller' => 'index' ), 'default', true);?>" method="post">
			
			<p>
				<label for="email"><?php echo $this->_("E-mail")?>:</label>
				<input class="text" name="email" id="email" type="text" value="" />
			</p>
			<p>
				<label for="password"><?php echo $this->_("Password")?>:</label>
				<input class="text" name="password" id="password" type="password" value="" />
			</p>
			
	
			<p>
				<input class="submit" type="submit" value="<?php echo $this->_("Login")?>" />
				<a href="<?php echo $this->url(array('action' => 'register' , 'controller' => 'index' ), 'default', true);?>" title="register"><?php echo $this->_("Sign up")?></a>
			</p>
			
		
		</form>
</div>


