<?php if( $this->success ) :?>
<div class=success>
	<?php echo( $this->success )?>
</div>
<?php endif;?>

<div id="error" style="display:none;"class="error">
</div>

<div id="panel">
<h2>TV Mundipharma Message</h2>

<form onsubmit="return check_form();" class="form" action="<?php echo $this->url(array('action' => 'postmessage' , 'controller' => 'index' ), 'default', true);?>" method="post">
		
		<p>
			<label for="comments"><?php echo $this->_("Content")?>:</label>
			<textarea class="textarea" name="content" id="content"></textarea>
			<span class="notice">The remain char is <span id="remain_word"></span></span>
		</p>

		<p>
			<label for="password"></label>
			<input class="submit" type="submit" value="<?php echo $this->_("Submit")?>" />
			<a class="link" href="<?php echo $this->url(array('action' => 'logout' , 'controller' => 'index' ), 'default', true);?>" title="logout"><?php echo $this->_("Logout")?></a>
			<a class="link" href="<?php echo $this->url(array('action' => 'password' , 'controller' => 'index' ), 'default', true);?>" title="change password"><?php echo $this->_("Change password")?></a>
			<?php 
			$userMod = Narrow_User_Factory::Factory();
			if($userMod->isLoginUserRole( Narrow_User_Imple::ROLE_ADMIN )):
			?>
			<a class="link" target="_blank" href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'index' , "module" => "admin" ), 'default', true);?>" title="admin panel"><?php echo $this->_("Admin")?></a>
		
			<?php endif;?>
		</p>

		
</form>
</div>

<script type="text/javascript">
//<!-- 
	var message_limit = 160;
	$('#content').textlimit('#remain_word',message_limit);

	function check_form(){



		var email = $("#content").val();
		var isEmpty = rocknoon.validate.is_empty( email );
		if( isEmpty ){
			show_error( "content_error" , '<?php echo $this->_("You should input a message!");?>' );
			return false;			
		}
		
		return true;
		
	}

	function show_error( id , error ){
	
		$("#error").html(error);
		$("#error").show(300);

	}


//--> 
</script>