
	<form class="form" style="width:450px;" onsubmit="return check_form();" action="<?php echo $this->url(array('action' => 'postchangepassword' , 'controller' => 'index' ), 'default', true);?>" method="post">
		<p>
			<?php echo $this->_("It's your first time Login. you can change your password")?>
		</p>
		
		<input type="hidden" name="code" value="<?php echo $this->code?>" />
		
		<p>
			<label for="password"><?php echo $this->_("Password")?>:</label>
			<input class="form_text" name="password" id="password" type="password" value="" />
			<label class="error" id="password_error"></label>
		</p>
		<p>
			<label for="password"><?php echo $this->_("Confirm Password")?>:</label>
			<input class="form_text" name="confirm_password" id="confirm_password" type="password" value="" />
			<label class="error" id="confirm_password_error"></label>
		</p>
		
		<p>
			<label for="password"></label>
			<input class="form_button" type="submit" value="<?php echo $this->_("Modify")?>" />
		</p>
		
	</form>

<script type="text/javascript">
//<!-- 

	function check_form(){


			var password = $("#password").val();
			var isEmpty = rocknoon.validate.is_empty( password );
			if( isEmpty ){
				show_error( 'password_error' , '<?php echo $this->_("You should input a new password");?>' );
				return false;			
			}

			var isPasswordSame = rocknoon.validate.is_same( $('#password').val() , $('#confirm_password').val());
			if( !isPasswordSame ){
				show_error( 'confirm_password_error' , '<?php echo $this->_('Password and confirmPassword should be same.') ?>');
				return false;
			}

			return true;
				
	}

	function show_error( id , error ){
		$("#password_error").html("");
		$("#confirm_password_error").html("");
		$("#" + id).html(error);

	}

//--> 
</script>