<div id="error" style="display:none;"class="error">
</div>

<div id="panel">
<h2>TV Mundipharma Password</h2>
	<form class="form" style="width:450px;" onsubmit="return check_form();" action="<?php echo $this->url(array('action' => 'postchangepassword' , 'controller' => 'index' ), 'default', true);?>" method="post">
		<?php if( $this->code ):?>
		<p>
			<?php echo $this->_("It's your first time Login. you can change your password")?>
		</p>
		<?php endif;?>
		
		<input type="hidden" name="code" value="<?php echo $this->code?>" />
		
		<p>
			<label for="password">
			<?php if( $this->code ):?>
				<?php echo $this->_("Password")?>:
			<?php else:?>
				<?php echo "Nieuw Wachtwoord"?>:
			<?php endif;?>
			</label>
			<input class="text" name="password" id="password" type="password" value="" />
		</p>
		<p>
			<label for="password">
			<?php if( $this->code ):?>
				<?php echo $this->_("Confirm Password")?>:
			<?php else:?>
				<?php echo "Bevestig Nieuw Wachtwoord"?>:
			<?php endif;?>
			</label>
			<input class="text" name="confirm_password" id="confirm_password" type="password" value="" />
		</p>
		
		<p>
			<label for="password"></label>
			<input class="submit" type="submit" value="<?php echo $this->_("Modify")?>" />
		</p>
		
	</form>
	
</div>

<script type="text/javascript">
//<!-- 

	function check_form(){


			var password = $("#password").val();
			var isEmpty = rocknoon.validate.is_empty( password );
			if( isEmpty ){
				show_error( 'password_error' , '<?php echo $this->_("You should input a new password");?>' );
				return false;			
			}

			var isPasswordSame = rocknoon.validate.is_same( $('#password').val() , $('#confirm_password').val());
			if( !isPasswordSame ){
				show_error( 'confirm_password_error' , '<?php echo $this->_('Password and confirmPassword should be same.') ?>');
				return false;
			}

			return true;
				
	}

	function show_error( id , error ){
		
		$("#error").html(error);
		$("#error").show(300);


	}

//--> 
</script>