<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style type="text/css"> 
.row{
clear:both;
}
</style>
<?php 
echo $this->headScript();
echo $this->headStyle();
echo $this->headLink(); 
echo $this->headTitle();
?>

<script type="text/javascript">
//<!-- 
var __BASE_URL__ = '<?php echo $this->baseUrl()?>';
//--> 
</script>
<link href="<?php echo $this->baseUrl()?>/css/backend.css" rel="stylesheet" type="text/css">
</head>
<body>

<div id="page">

	<div id="sidebar">
	  <h3><?php echo $this->_('Menu')?></h3>
	  <ul id="sidebar-items">
	  		<li><a href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'user' , 'module' => 'admin' , 'status' => Narrow_User_Imple::STATUS_WAITING ), null, true);?>"><?php echo $this->_('User')?></a></li>
	  		<li><a href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'message' , 'module' => 'admin'), null, true);?>"><?php echo $this->_('Message')?></a></li>
	  </ul>
	</div>

	<div id="body">
		<div id="customize">
	
		</div>
		<?php echo $this->layout()->content ?>
	</div>
</div>

</body>
</html>