<h3><?php echo $this->_('Message View Panel'); ?></h3>
<br/><br/>

<form class="form" action="<?php echo $this->url(array(
		'controller' => 'message', 
		'action' => 'postsave', 
		'module' => 'admin'
		), null , true);?>" method="post" id="form">

<input type="hidden" name="id" value="<?php echo $this->message['id']; ?>"/>

<p>
<label><?php echo $this->_('User'); ?></label>
<?php 
	$userMod = Narrow_User_Factory::Factory();
	$user = $userMod->getById( $this->message['user_id'] );
	echo $user['first_name'];
?>
</p>

<p>
<label><?php echo $this->_('Create Time'); ?></label>
<?php 
	echo date( "Y-m-d" , $this->message['date_add'] );
?>
</p>

<p>
<label><?php echo $this->_('Content'); ?></label>
<textarea id="content" name="content"><?php echo htmlspecialchars_decode(stripslashes($this->message['content'])); ?></textarea>
<br/><label></label>remain chars <span id="remain_word"></span>
</p>


<p>
<label></label>
<input type="submit" value="<?php echo $this->_('Submit'); ?>" />
</p>


</form>

<script type="text/javascript">
//<!-- 

	var message_limit = 160;
	$('#content').textlimit('#remain_word',message_limit);

//--> 
</script>
