<h3><?php echo $this->_('Message Panel'); ?></h3>
<br/><br/>


<!-- view status -->



<a 
href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'message' , 'module' => 'admin' , 'status' => 'all' ), null, true);?>" title="all" 
<?php if( $this->status != null && $this->status   == 'all' ):?>
	class = 'current' 
<?php endif;?>
><strong><?php echo $this->_('All'); ?></strong></a>&nbsp;&nbsp;&nbsp;&nbsp;

<a 
href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'message' , 'module' => 'admin' , 'status' => 'approved' ), null, true);?>" title="all" 
<?php if( $this->status  == 'approved' ):?>
	class = 'current' 
<?php endif;?>
><strong><?php echo $this->_("Approved")?></strong></a>&nbsp;&nbsp;&nbsp;&nbsp;

<a 
href="<?php echo $this->url(array('action' => 'index' , 'controller' => 'message' , 'module' => 'admin' , 'status' => 'rejected' ), null, true);?>" title="all" 
<?php if( $this->status  == 'rejected' ):?>
	class = 'current' 
<?php endif;?>
><strong><?php echo $this->_("Rejected")?></strong></a>&nbsp;&nbsp;&nbsp;&nbsp;



<br/><br/>

<?php if( count( $this->messages ) == 0 ):?>
	<?php echo $this->_("There is no messages.")?>
<?php else:?>

<table width="100%">
<tr class="head">
    <td style="width:300px;"><?php echo $this->_('Content');?></td>
    <td><?php echo $this->_('Author');?></td>
    <td><?php echo $this->_('Time');?></td>
    <td><?php echo $this->_('Action');?></td>
</tr>



<?php
foreach($this->messages as $message ):
?>
<tr>
	<td><?php echo $message['content']; ?></td>
	<td><?php 
	$userMod = Narrow_User_Factory::Factory();
	$user = $userMod->getById( $message['user_id'] );
	echo $user['first_name']." ".$user['last_name']; ?></td>
	<td><?php echo date( "Y-m-d" , $message['date_add'] ); ?></td>
	<td>
		<a href="javascript:void(0);" onclick="message_edit(<?php echo $message['id']?>);"><?php echo $this->_('Edit');?></a> |
		<a href="javascript:void(0);" onclick="message_delete(<?php echo $message['id']?>);"> <?php echo $this->_('Delete');?></a>|
		
		<?php if( !$message["approved"] ):?>
		<a href="javascript:void(0);" onclick="message_approve(<?php echo $message['id']?> , 1);"> <?php echo $this->_('Approve');?></a>
		<?php else:?>
		<a href="javascript:void(0);" onclick="message_approve(<?php echo $message['id']?> , 0);"> <?php echo $this->_('Reject');?></a>
		<?php endif;?>
	</td>
</tr>
<?php
endforeach;
?>
<tr>
	<td colspan='6'>&nbsp;</td>
</tr>
</table>

<?php echo $this->paginationHTML ?>


<?php endif;?>

<script>

	function message_edit( id ){
		
		location.href = __BASE_URL__ + "/admin/message/edit/id/" + id;
		
	}

	function message_delete( id , role ){
		var answer = confirm("<?php echo $this->_("Are you sure you want to delete this message? ")?>");
		if(answer){
			location.href = __BASE_URL__ + "/admin/message/postdelete/id/" + id;
		}
	}

	function message_approve( id , flag ){
		location.href = __BASE_URL__ + "/admin/message/poststatus/id/" + id + "/approve/" + flag;	
	}

</script>

